SET AUTOTRACE ON;
ALTER SESSION SET STATISTICS_LEVEL='ALL';


-- Cada vez que haga una busqueda, vacia la RAM
ALTER SYSTEM FLUSH SHARED_POOL;
ALTER SYSTEM FLUSH BUFFER_CACHE;


--SELECT COUNT(*) FROM PRUEBA WHERE CLAVE = 50000;
--SELECT COUNT(*) FROM PRUEBA WHERE DISPERSO = 50000;
--SELECT COUNT(*) FROM PRUEBA WHERE CONCENTRADO = 5;
--SELECT COUNT(*) FROM PRUEBA WHERE IDISPERSO = 50000;
--SELECT COUNT(*) FROM PRUEBA WHERE ICONCENTRADO = 5;
--SELECT COUNT(*) FROM PRUEBA WHERE BCONCENTRADO = 5;

--UPDATE PRUEBA SET DISPERSO = DISPERSO + 7;
--UPDATE PRUEBA SET IDISPERSO = IDISPERSO + 7; 

SELECT COUNT(*) FROM PRUEBA WHERE IDISPERSO BETWEEN 10000 AND 20000;
