SQL PLUS / AS SYSTEM WALLET_ROOT.SQL

NET STOP OracleServiceORCL

NET START OracleServiceORCL

SQLPLUS / AS SYSDBA TDE.SQL

SQLPLUS / AS SYSKM KEYSTORE_AUTOLOGIN.SQL

SQLPLUS / AS SYSTEM CREAR LIFEFIT

SQLPLUS / AS SYSDBA CREAR_ESQUEMA.SQL